### ISSUE TITLE
How to code for other languages?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [X-Wei/widget_with_codeview#2]
Can this library be used to show codes of other languages as well? 
If not then please recommend something else.

**Comment by X-Wei** [comment]
I think for other languages you can modify the keywords in [syntax_highligher.dart](https://github.com/X-Wei/widget_with_codeview/blob/3a5b6ce4e5db72d7d0c6c0861ef53fb1712ba9d2/lib/syntax_highlighter.dart#L66)
