### ISSUE TITLE
window.dart:519 Error while trying to load an asset: Failed to load asset at "assets/demo.dart" (404)

### ISSUE THREAD

**Issue by hiashutoshsingh** [X-Wei/widget_with_codeview#7]
I can't see my source code despite giving correct file path in the widget and in pubspec file also.

What i cam doing wrong here?

pubspec.yaml
```
flutter:
  assets:
    - lib/
    - assets/demo.dart
```

dart file
```
SourceCodeView(
filePath: 'demo.dart',
codeLinkPrefix:
'https://github.com/X-Wei/widget_with_codeview/blob/master/lib/source_code_view.dart',
 )
```

assets path
<img width="253" alt="Screenshot 2021-01-11 at 4 23 07 PM" src="https://user-images.githubusercontent.com/21235425/104171844-4bfa0180-5429-11eb-8f0c-a890bec91c3c.png">

**Comment by X-Wei** [comment]
The filePath should include the "assets/" prefix:

```dart
SourceCodeView(
  filePath: 'assets/demo.dart',
  codeLinkPrefix: 'https://github.com/X-Wei/widget_with_codeview/blob/master/', // you can also omit this arg.
 )
```
